FROM ubuntu:20.04

RUN apt update && apt upgrade -y

RUN apt install bind9 bind9utils bind9-doc dnsutils -y

RUN apt install -y systemctl

RUN mkdir /etc/bind/keys

COPY named.conf.local /etc/bind
COPY named.conf.options /etc/bind
COPY m1-8.ephec-ti.be /etc/bind

EXPOSE 53/udp
EXPOSE 53/tcp

CMD ["named", "-g"]
