FROM php:7.2-apache

RUN apt update -y && apt upgrade -y
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt install openssl

COPY config_files/www.m1-8.ephec-ti.be.conf /etc/apache2/sites-available
COPY config_files/b2b.m1-8.ephec-ti.be.conf /etc/apache2/sites-available

RUN ln -s /etc/apache2/sites-available/www.m1-8.ephec-ti.be.conf /etc/apache2/sites-enabled
RUN ln -s /etc/apache2/sites-available/b2b.m1-8.ephec-ti.be.conf /etc/apache2/sites-enabled

RUN mkdir /var/www/b2b.m1-8.ephec-ti.be
RUN mkdir /var/www/www.m1-8.ephec-ti.be

COPY /sites/www/index.html /var/www/www.m1-8.ephec-ti.be
COPY /sites/b2b/index.php /var/www/b2b.m1-8.ephec-ti.be

COPY /certif/cert.pem /etc/ssl/certs/cert.pem
COPY /certif/cert-key.pem /etc/ssl/certs/cert-key.pem

RUN a2enmod ssl
RUN service apache2 start